Listados/Models/AsignarContenedor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Listados.Models
{
    public class AsignarContenedor
    {
        public List<AssignarContenedorInstruccionEmbarqueViewModel> Contenedores { get; set; }
    }
}

Listados/Controllers/DetalleContenedoresViewController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Listados.Db;
using Listados.Models;

namespace Listados.Controllers
{
    public class DetalleContenedoresViewController : Controller
    {
        // GET: DetalleContenedoresView
        public ActionResult Index()
        {
            using (var contextxportaciones = new ExportacionesEntities())
            {
                var listaDeContentendores = contextxportaciones.Contenedores.Select
                    (AutoMapper.Mapper.Map<DetalleContenedoresViewModel>).ToList();
                return View(listaDeContentendores);
            }
    }
        [HttpGet]
        public ActionResult IndexModal()
        {
            using (var contextxportaciones = new ExportacionesEntities())
            {
                var detalleContenedores = contextxportaciones.Contenedores.Select(AutoMapper.Mapper.Map<DetalleContenedoresViewModel>).ToList();
                return PartialView(detalleContenedores);
            }

         
        }
    }


}

Listados/Controllers/InstruccionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Listados.Db;
using Listados.Models;

namespace Listados.Controllers
{
    public class InstruccionController : Controller
    {
        //private ExportacionesHCFEntities db = new ExportacionesHCFEntities();


        // GET: Instruccion
        public ActionResult Index()
        {
            using (var contextxportaciones = new ExportacionesEntities())
            {
                var listaDeInstruccionesDeEmbarque = contextxportaciones.InstruccionEmbarque.Select(AutoMapper.Mapper.Map<InstruccionesEmbarqueViewModel>).ToList();
                return View(listaDeInstruccionesDeEmbarque);
            }
        }

        public ActionResult AddRowContenedor(int count)
        {
            ViewBag.Count = count;
            return PartialView();
        }

        [HttpGet]
        public ActionResult AsignarContenedor(int id)
        {
            ViewBag.IdInstruccion = id;
            return View();
        }

        [HttpPost]
        [ValidateInput(true)]
        public ActionResult AsignarContenedor(int id, AsignarContenedor model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Error = "error message";
            }
            else
            {
                model.Contenedores.ForEach(x => x.IdInstruccion = id);
                var listaDeRespuestas = model.Contenedores.Select(AsignarContenedor).ToList();
            }

            return View(model);

        }


        public AsingarContenedorResponse AsignarContenedor(AssignarContenedorInstruccionEmbarqueViewModel model)
        {
            using (var contextExportaciones = new ExportacionesEntities())
            {
          
                try
                {
                    if (!contextExportaciones.Contenedores.Any(x=>x.IdInstruccion==model.IdInstruccion && x.NContenedor==model.NroContenedor))
                    {                      
                        var contenedor = AutoMapper.Mapper.Map<Contenedores>(model);
                      contextExportaciones.Contenedores.Add(contenedor); 
                       var result = contextExportaciones.SaveChanges() > 0;
                        return new AsingarContenedorResponse { Creado = result, Mensaje = result ? "Se ha creado con exito" : "No se pudo crear" };
                    }
                    else
                    {
                        return new AsingarContenedorResponse { Creado = false, Mensaje = "No se pudo crear, porque ya existe" };
                    }
                }
                catch (Exception ex)
                {
                    return new AsingarContenedorResponse { Creado = false, Mensaje = ex.Message };
                }
            }
        }

    
        // GET: Instruccion/Create
        //public ActionResult Create()
        //{
        //    using (var contextxportaciones = new ExportacionesEntities())
        //    {
        //        ViewBag.SelectConsignee = contextxportaciones.Consignee.ToList().Select(x => new SelectListItem {Text = x.Consignee1, Value=x.IdConsignee.ToString() });
        //        ViewBag.SelectDetalleContrato = contextxportaciones.DetalleContrato.ToList().Select(x => new SelectListItem {Text = x.Contratos.CodContrato, Value=x.IdDetalleContrato.ToString() });
        //        ViewBag.SelectLineas = contextxportaciones.Lineas.ToList().Select(x => new SelectListItem {Text = x.Linea, Value=x.IdLinea.ToString() });
        //        ViewBag.SelectNavieras = contextxportaciones.Navieras.ToList().Select(x => new SelectListItem {Text = x.Naviera, Value=x.IdNaviera.ToString() });
        //        ViewBag.SelectPuertoCarga = contextxportaciones.Puertos.ToList().Select(x => new SelectListItem {Text = x.Puerto, Value=x.IdPuerto.ToString() });
        //        ViewBag.SelectPuertoDescarga = contextxportaciones.Ciudad.ToList().Select(x => new SelectListItem {Text = x.Ciudad1, Value=x.IdCiudad.ToString() });
        //        ViewBag.SelectTerminoBl = contextxportaciones.TerminoBl.ToList().Select(x => new SelectListItem {Text = x.TerminoBl1, Value=x.IdTerminoBl.ToString() });
        //        return View();
        //    }               
        //}


    }
}

Listados/Views/Instruccion/AddRowContenedor.cshtml
 <tr>
        <td>
            <input class="form-control" name="Contenedores[@ViewBag.Count].NroContenedor"
                   id="NroContenedor" type="text" />
        </td>
        <td>
            <input class="form-control" name="Contenedores[@ViewBag.Count].Sello"
                   id="Sello" type="text" />
        </td>
        <td>
            <input class="form-control" name="Contenedores[@ViewBag.Count].Tara"
                   id="Tara" type="text" />
        </td>
        <td>
            <input class="form-control" name="Contenedores[@ViewBag.Count].PesoMaximo"
                   id="PesoMaximo" type="text" />
        </td>
        <td>
            <button class="btn btn-danger btn-sm" id="deleteRow">
                Eliminar
            </button>
        </td>
    </tr>
    
<script>

   

</script>

Listados/Views/Instruccion/AsignarContenedor.cshtml
@model Listados.Models.AsignarContenedor

@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>*@
<div class="col-lg-12">
    <form action="@Url.Action("AsignarContenedor", "Instruccion", new { id = ViewBag.IdInstruccion })" method="post">
        </br>
        <table class="table table-responsive table-bordered" id="TablaDeContenedorPorInstruccionDeEmbarque" data-count="0">
            <thead>
                <tr>
                    <th id="NroContenedor">Nro. Contenedor</th>
                    <th>No. Sello</th>
                    @Html.ValidationMessageFor(m => m.Contenedores)
                    <th>Tara</th>
                    @Html.ValidationMessageFor(m => m.Contenedores)
                    <th>Peso Maximo</th>
                    <th><button class="btn btn-primary btn-sm"  type="button" id="AgregarLineaTabla"><i class="glyphicon glyphicon-plus"></i> Agregar</button></th>
                </tr>
            </thead>
            <tbody>

             
            </tbody>
        </table>
        <div>
            <button class="btn btn-success" type="submit" id="GuardarContenedores"> Guardar </button>
        </div>
    </form>
    <br />
</div>

@section scripts{

    <script>
    
        //$("#deleteRow").on("click", function () {
        //    alert("deleteRow");
        //    return false;
        //})

        //$('#GuardarContenedores').on('click', function () {
        //    if ($('#NroContenedor') || $('#Sello') || $('#Tara') || $('#PesoMaximo').val().length == 0) {
        //        alert('Please fill out your initials.');
        //        console.log(NroContenedor);
        //        return false;
        //    }
        //});
        //var table = $('#TablaDeContenedorPorInstruccionDeEmbarque').DataTable();
        //$('#TablaDeContenedorPorInstruccionDeEmbarque').on('click', '#deleteRow', function () {
        //    table
        //    .row($(this).parents('tr'))
        //    .remove()
        //    .draw();
        //});

        $("#AgregarLineaTabla").on("click", function () {
            var count = $("#TablaDeContenedorPorInstruccionDeEmbarque").attr("data-count");
            $.ajax({
                url: "@Url.Action("AddRowContenedor", "Instruccion")",
                data: { count: count },
                type: "GET",
                success: function (resp) {
                    $("#TablaDeContenedorPorInstruccionDeEmbarque tbody").append(resp);
                    $("#TablaDeContenedorPorInstruccionDeEmbarque").attr("data-count", (parseInt(count) + 1));
                }
            })
        });


        function Post() {
            var contenedores = [];
            $("#TablaDeContenedorPorInstruccionDeEmbarque tr").each(function () {
                var obj = new Object();

                var name = $(this).find("input").each(function () {

                    if (this.id == 'NroContenedor' && this.value != '') {
                        obj.NroContenedor = this.value;
                    }
                    else if (this.id == 'Sello' && this.value != '') {
                        obj.Sello = this.value;
                    }
                    else if (this.id == 'Tara' && this.value != '') {
                        obj.Tara = this.value;
                    }
                    else if (this.id == 'PesoMaximo' && this.value != '') {
                        obj.PesoMaximo = this.value;
                    }

                });
                contenedores.push(obj);
            });
            contenedores = JSON.stringify({ contenedores: contenedores });
            $.ajax({
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                type: 'POST',
                url: '/Instruccion/AsignarContenedor',
                data: contenedores
            });
        }



    </script>




}

Listados/Views/Instruccion/Index.cshtml
@model IEnumerable<Listados.Models.InstruccionesEmbarqueViewModel>
<script async="" src="//www.google-analytics.com/analytics.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>

<script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@*<button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModalDetalleContenedores">Open Modal</button>*@
@*@Html.ActionLink("Detalle de contenedores", "IndexModal", "DetalleContenedoresView", null, new { @class = "img-btn-addcontent modal-link" })*@
@*<button href="#myModal" id="openBtn" data-toggle="modal" class="btn btn-default">Modal</button><div class="modal fade" id="myModal" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 class="modal-title">Big Title</h3>
                </div>        <div class="modal-body">
                    <h5 class="text-center">Hello. Some text here.</h5>          <table class="table table-striped" id="tblGrid">            <thead id="tblHead">              <tr>                <th>Location</th>                <th>Points</th>                <th class="text-right">Mean</th>              </tr>            </thead>            <tbody>              <tr><td>Long Island, NY, USA</td>                <td>3</td>                <td class="text-right">45001</td>              </tr>              <tr><td>Chicago, Illinois, USA</td>                <td>5</td>                <td class="text-right">76455</td>              </tr>              <tr><td>New York, New York, USA</td>                <td>10</td>                <td class="text-right">39097</td>              </tr>            </tbody>          </table>          <div class="form-group">            <input class="btn btn-warning btn-sm pull-right" value="Reset" type="button">            <div class="clearfix"></div>          </div>
                </div>        <div class="modal-footer">          <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>          <button type="button" class="btn btn-primary">Save Changes</button>        </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->*@





<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdInstruccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NroContrato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Referencia)
        </th>
        <th></th>
    </tr>

    <div>
        <li>
            @Html.ActionLink("Detalle Contenedores", "index", "DetalleContenedoresView")
        </li>
    </div>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdInstruccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NroContrato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Referencia)
            </td>
            <td>
                @Html.ActionLink("Asignar Contenedores", "AsignarContenedor", new { id = item.IdInstruccion })
                @Html.ActionLink("Index", "Instruccion")

            </td>
        </tr>
    }

</table>

@*PRIMER MODAL*@
<div id="modal-container" class="modal fade"
     tabindex="-1" role="dialog">
    <div class="modal-content">
    </div>
</div>

@*SEGUNDO MODAL*@
<button type="button" class="btn btn-success" data-toggle="modal" id="btnShow" data-target="#myModalDetalleContenedores">Mostrar contenedores</button>
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog" id="bodymodal">
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(function () {
            $("#btnShow").click(function () {
                $('#myModal').modal('show');
                $.ajax({
                    url: "@Url.Action("IndexModal", "DetalleContenedoresView")",
                    
                type: "GET",
                success: function (resp) {
                    $("#bodymodal").html(resp);
                }
            })
            });
        });
    </script>
}